[package]
name = "netctl-tray"
version = "0.1.0"
authors = ["Ponas <mykolas.peteraitis@gmail.com>"]
edition = "2018"

[dependencies]
qt_widgets = "0.3.0"
qt_gui = "0.3.0"
notify-rust = "3.6.2"
regex = "1.3.1"